### ISSUE TITLE
Open-BPMN keeps loading forever

### ISSUE THREAD

**Issue by Fede-Berga** [imixs/open-bpmn-vscode-integration#36]
Hello everyone.
I have been trying to use your VsCode extension to draw some diagram.
The result is that it keeps loading forever, even on an empty diagram.

[![](https://github.com/user-attachments/assets/57c71292-7fe6-438b-b9fb-ada4420a9483)](https://github.com/user-attachments/assets/57c71292-7fe6-438b-b9fb-ada4420a9483)

**Comment by rsoika** [comment]
Hi @Fede-Berga did you have a Java VM installed on your system? Open-BPMN requires JDK 17.
See also here: https://marketplace.visualstudio.com/items?itemName=open-bpmn.open-bpmn-vscode-extension

**Comment by Fede-Berga** [comment]
Hi @rsoika, that worked perfectly!
